import '../styles/globals.css';
import Head from 'next/head';
import Layout from '../components/Layout/Layout';

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </div>
  );
}

export default MyApp;
